### ISSUE TITLE
RTFEdit does not work

### ISSUE THREAD

**Issue by wagy** [RDashINC/phc-win#6] opened 2015-02-27 15:54 UTC
```
embeder2.exe new rtfedit
embeder2.exe type rtfedit CONSOLE
embeder2.exe main rtfedit rtfedit.phpw
```

When i test with the example rtfedit.phpw 

`Warning: wbCreateControl: Error creating control of class 24 ('RichEdit41')`
Result: the rtfedit control ist not in the window

Then i go back to VC11 and make winbinder shared and load on runtime the prebuild extension
 winbinder_56_TS.dll from stefan-loewe 
Now the rtfedit example works.
Is this a problem on the configuration ?

**Comment by RainbowDashDC** [comment] 2015-02-28 01:24
This is probably a bug with the static extension. Did you build from source or use prebuild?

Also, can you provide rtfedit's src so I can debug with it.

**Comment by wagy** [comment] 2015-02-28 07:50
This is probably a bug with the static extension. Did you build from source or use prebuild?
From source

The Problem is 'RichEdit41'  this is the XP Version
On wb.h i change to      #define RICHEDITCONTROL            TEXT("RICHEDIT50W")
Then the control is open,  bad the rtftext inside is :
{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\froman\fprq2\fcharset0 Times New Roman;}}
{\colortbl ;\red128\green0\blue0;\red0\green0\blue255;}
\viewkind4\uc1\pard\cf1\b\f0\fs20 Hello\cf0\b0 ,\par
\pard\fi568 This is a \i "test" \i0\f1 (Rich Text)\f0 .\par
\pard\par
\cf2\fs16 This text was generated on WordPad.\cf0\fs20\par
}

Maybe we need some libs  ??
I have inserted to     wb.h #pragma comment(lib,"msftedit.lib")
The same result

**Comment by RainbowDashDC** [comment] 2015-02-28 19:01
Can't reproduce, it won't even load winbinder because dirname(__FILE__) doesn't point to the DIR.

**Comment by RainbowDashDC** [comment] 2015-02-28 19:42
Alright, reproduced. Working on it, but it seems to be winbinders problem regardless of static or shared. So, will try to fix.

**Comment by RainbowDashDC** [comment] 2015-02-28 21:53
stefan-loewe/WinBinder#9 fixes this, but I won't close this until it's merged also, latest commit to PHC-WIN fixes .phpw extensions. Thanks for the report!

If you want to manually apply the fixes, clone RDashINC/WinBinder into ext/winbinder instead.

**Comment by RainbowDashDC** [comment] 2015-03-02 15:54
Merged in master of WinBinder. Closed.

**Closed by RainbowDashDC** 2015-03-02 15:54 UTC
Labels: critical

**Comment by wagy** [comment] 2015-03-02 17:32
Am 02.03.2015 um 16:55 schrieb Jared Allard:
>
> Merged in master of WinBinder. Closed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RDashINC/phc-win/issues/6#issuecomment-76737133>.
>
Yes it works thank you.

**Comment by RainbowDashDC** [comment] 2015-03-02 17:58
@wagy Glad to hear it! Best of luck!
